### ISSUE TITLE
ImportError when loading bw2data

### ISSUE THREAD

**Issue by SanderNielen** [brightway-lca/brightway-live#43]
I encountered different issues when loading `bw2data` in the test-notebook. First, I had to little memory available, but that was fixed by closing some other browser tabs. Then this popped up:
`ImportError: dynamic module does not define module export function (PyInit_interval)`
Hopefully, there's a way around this!

**Comment by michaelweinold** [comment]
Hey, @SanderNielen - could you let us know what command let to that error?

**Comment by SanderNielen** [comment]
Yes, it was the command `import bw2data`.

**Comment by michaelweinold** [comment]
Unable to reproduce on the latest version - following the installation commands in the notebooks should work fine.
