### ISSUE TITLE
workaround for https not working with requests module

### ISSUE THREAD

**Issue by mike-kfed** [brightway-lca/brightway-live#46]
requests cannot do https, but using pyodide's open_url does. here's a workaround that can be applied to everywhere requests is used. `open_url()`  returns a StringIO, therefore it needs to be json decoded and is then available. proper fix is likely a wrapper function doing that for us, anyways here the fix for 2nd notebook the "Interfaces" section:

```
from pyodide.http import open_url
import json
class DenmarkCO2Interface:
    size = (1,)

    def __next__(self):
        # Supposed to work with ISO 8601 but T intervals raise error...
        URL = "https://api.energidataservice.dk/dataset/co2emis?start=now-P1D&end=now"
        print("Querying energidataservice.dk API")
        #result = requests.get(URL).json()['records'][0]['CO2Emission']
        result = open_url(URL)
        #print(result.getvalue())
        data = json.load(result)['records'][0]['CO2Emission']
        print(data)
        return np.array([data]) / 1000 # g to kg
```

**Comment by mike-kfed** [comment]
issue #16 mentions the requests module problem already, I just noticed, sorry for double post

**Comment by michaelweinold** [comment]
Thank you for posting this workaround! While I was aware of the `requests` limitation, I didn't know `open_url` from `pyodide.http` could work instead. We'll try to use this in some of the functions using `requests` (such as [`bw2io.useeio11()`](https://github.com/brightway-lca/brightway2-io/blob/a7e62fe507935ce45c54d2d93ac42da245a1a306/bw2io/__init__.py#L157)).

**Comment by michaelweinold** [comment]
`requests` support should have been added:

[2023 Pyodide documentation](https://web.archive.org/web/20230603010901/https://pyodide.org/en/stable/project/roadmap.html#write-http-client-in-terms-of-web-apis) vs [2024 Pyodide documentation](https://pyodide.org/en/stable/usage/wasm-constraints.html#synchronous-http-requests-support)

**Comment by michaelweinold** [comment]
`requests` [was added to Pyodide in `0.25.0`](https://pyodide.org/en/stable/project/changelog.html#packages) - and it works great 🎉
